MAKE can be the sequence of commands

diff --git a/bench-git b/bench-git
--- a/bench-git
+++ b/bench-git
@@ -72,7 +72,7 @@ write_bench_data() {
             continue
         fi
         set_revision "$wc" "$rev" || { rm $tmp; die "can't checkout $rev"; }
-        (cd "$wc/$CD" && $MAKE) || { rm $tmp; die "can't make"; }
+        (cd "$wc/$CD" && echo "$MAKE" | sh) || { rm $tmp; die "can't make"; }
         if eval $BENCH $bench_opt $PROGRAM > "$tmp" ; then
             grep '=' $tmp | sed "s/^/rev${rev}_/" >> "$data_file"
             sleep 1
